name: Test CD

on:
  push:
    branches: [ master ]

env:
  SERVER_HOST: 91.200.151.163
  SERVER_USERNAME: root
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}


jobs: 
  build:

    runs-on: ubuntu-latest
 
    steps:
    - name: Connect to server and deploy changes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SERVER_HOST }}
        username: ${{ env.SERVER_USERNAME }}
        key: ${{ env.SSH_PRIVATE_KEY }}
        script: |
          cd ~/med_crm_admin_sakai/
          git pull
          npm install
          ng build
          sudo rsync -av --delete /root/med_crm_admin_sakai/dist/med-admin/ /var/www/med_crm_admin/